services:
  web:
    volumes:
      - ./src:/var/www/html:cached

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pet-system-api-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
